#ifndef	__CONSTANTES_H__
#define __CONSTANTES_H__

#define	DEFAULT_INTERVAl_CLICK_SEC	0
#define	DEFAULT_INTERVAl_CLICK_uSEC	400000

#define	DEFAULT_INTERVAl_DBLCLICK_SEC	0
#define	DEFAULT_INTERVAl_DBLCLICK_uSEC	400000

#endif
